### ISSUE TITLE
The source and destination cannot both be remote

### ISSUE THREAD

**Issue by shivapoudel** [razor-x/config_curator#10]
![capture](https://cloud.githubusercontent.com/assets/3774827/9706155/ced5fd98-54fc-11e5-929d-892b1017bd09.PNG)

My configuration, but components section only set `~/.dotfiles/.vim` empty directory while using Window OS (It was the first great tool for dotfiles, so please add support components in Windows):

``` yml

---
root: "~/.dotfiles"

components:
  - src: vim/vim
    dst: .vim

config_files:
  - src: bash/bash_profile
    dst: .bash_profile

  - src: bash/bashrc
    dst: .bashrc

  - src: git/gitconfig
    dst: .gitconfig

  - src: git/gitignore_global
    dst: .gitignore_global

  - src: mintty/minttyrc
    dst: .minttyrc

  - src: npm/npmrc
    dst: .npmrc

  - src: vim/vimrc
    dst: .vimrc
```
